### PR TITLE
Allow irregular fvar instance names

### PR DESCRIPTION
**Pull request by yanone**
I got [notified](https://github.com/google/fonts/pull/6961#issuecomment-1812531089) that Honk may carry irregular instance names.

I updated the files accordingly. Please merge this PR for the onboarding process to be able to pull the latest files from the repository.

Thank you.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@yanone you may want to add these names and values to the STAT table for apps like MS Words to be able to display them (so in the config.yaml file)

**Comment by yanone** [comment]
@RosaWagner The default instance is called "Regular" in their font, whereas according to the axis registry it should be called "Default". Can it be named Regular?

**Comment by RosaWagner** [comment]
Yes, but you would need elide the 2 default values with `flags: 2`

**Comment by yanone** [comment]
🫣

**Comment by RosaWagner** [comment]
Looks good now 👍

**Pull request merged**
